/*
 * This source file was generated by the Gradle 'init' task
 */

package com.example;

import java.util.Scanner;

public class App {
public static void main(String[] args) {
Scanner scanner = new Scanner(System.in);
System.out.println("South African ID Validator");
System.out.println("-------------------------");
System.out.println("Enter a 13-digit ID number to validate (or 'quit' to exit):");

while (true) {
System.out.print("ID: ");
String input = scanner.nextLine().trim();

if (input.equalsIgnoreCase("quit")) {
System.out.println("Exiting validator. Goodbye!");
break;
}

boolean isValid = org.example.ValidateSaId.isIdNumberValid(input);
System.out.printf("ID: %s -> %s%n", input, isValid ? "Valid" : "Invalid");
}

scanner.close();
}
}
